### ISSUE TITLE
Use transform to improve fzf

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#3]
fzf released a new transform action to conditionally perform a series of actions:
https://github.com/junegunn/fzf/releases/tag/0.45.0

-  A single key binding to toggle between modes (toggle tmux sessions, zoxide results, find, and all with ctrl+a?)
- Use transform to take the value and transform it before moving onto the `sesh connect` command (transform to json?)
- Disallow selecting an empty line
- Consider backwards compatibility, for those that don't upgrade to fzf `0.45.0`
- Figure out how to get tell a user that upgrading to fzf `0.45.0` will give them a new feature (`sesh tui`?)

**Comment by Tanish2002** [comment]
Hey! I just saw this project. Great work 😄

I was wondering why are we depending on `fzf` for this project? I understand `zoxide` and `tmux` since they are essential for this plugin, but fzf is just for selecting a session/folder from a list.

Haven't looked at the code much, but I think we could use [go-fuzzyfinder](https://github.com/ktr0731/go-fuzzyfinder). 
So the actual command could go from `sesh connect (sesh list | fzf)` to just `sesh connect`.
Where if no args are passed then it opens a fuzzy-finder list, else if args are passed then it works like now.

Also, go-fuzzyfinder seems to have support for prompts, and preview panes which could be useful I believe.

**Comment by joshmedeski** [comment]
Thanks!

So I want to keep the project simple right now, and let others provide their own fzf-like tool and configure it however they'd like.

Thanks for the research, I've been looking too and perhaps I'll add dependency free fzf support to the project but I have more features I'd like to focus on.

**Comment by Tanish2002** [comment]
Yeah sure, fzf is great 😄. I believe most devs would have it installed anyway.

Though I do think it would be nice to have in the future.

**Comment by Tanish2002** [comment]
Yeah.
We could keep it backward compatible as well by keeping the `sesh list` command as it is so users can pipe it to whatever fuzzy finder they like.

Do ping me if you want me to look into any features/issues currently haha!

**Comment by joshmedeski** [comment]
Thanks! There's still more work to be done with porting over the "t" tmux plugins functionality. So feel free to look at the issues for this project and let me know if any peak your interest.

**Comment by joshmedeski** [comment]
I'm going to drop fzf from the project right now and allow people to add their own fzf integration that they see fit (see the suggestions in the README)
