### ISSUE TITLE
doesn't connect to first session

### ISSUE THREAD

**Issue by znd4** [joshmedeski/sesh#76]
### What happened?

when I run `sesh connect nixfiles`, I end up with a new session in `/home/$USER` with name `$USER` instead of connecting to my existing session named `nixfiles` (which shows up in `sesh list -t`

`sesh connect` works as expected with every other session (including `sesh connect $USER`).

I think the important detail here is that `nixfiles` is the first session -- my default wezterm program is (almost)

```
tmux new -Asnixfiles
```

EDIT: Extra debugging: I killed the existing `nixfiles` and `$USER` sessions, ran `sesh connect ~/path/to/nixfiles` at which point `sesh connect` worked for all sessions.

I suppose it might be possible as a workaround to write a tmux entry script that always kills the first session, but it seems like a bit of a headache

### Version

dev (I'm building from source, currently locked to `be2badd29206f66803b76b62b23f6f5e05befe08`)

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
Okay, so I know what is happening.

The intention of sesh is for every session name to be identical to the directory it's pointed to. So the logic currently looks up if a tmux session exists [by the path of the tmux session](https://github.com/joshmedeski/sesh/blob/3a7d0354c3b73c96ba6f59a3bb4ce924e61eb4ef/session/path.go#L33), not the session name.

In your case, the `nixfiles` session is pointing to the `$HOME` directory and generating a new session based off your user name, not the custom name you defined.

The reason I did this was to make it easier to identify a tmux session from a zoxide result, rather than having to convert a zoxide result into a session name before doing the comparison.

I do recommend you avoid custom tmux sessions names when using sesh and always allow sesh to be the one to name tmux sessions on your behalf.

Would you like sesh to behave differently? I'm open to changing it if it works well for the sesh community.

**Comment by bchubb-web** [comment]
I have encountered this aswell, my idea would be to rename the 0 session on the first opening of sesh, to its folder name

**Comment by joshmedeski** [comment]
My start script does something very similar, glad to clarify things.

And yes, sessions have a `session_path` assigned on creation:

<img width="727" alt="image" src="https://github.com/joshmedeski/sesh/assets/2036594/d5809abe-1f41-49da-9a88-b1bbf7c4401f">
